import ReactFlow, {
  MiniMap,
  Controls,
  useNodesState,
  useEdgesState,
} from "reactflow";
import Head from "next/head";

import "reactflow/dist/base.css";
import "@/styles/globals.css";

import CustomNode from "@/components/CustomNode";
import { disciplines } from "@/disciplines.js";

const nodeTypes = {
  custom: CustomNode,
};

let initNodes = [];
let x, y;
x = y = 0;

for (let id = 0; id < disciplines.length; id++) {
  if (disciplines[id].code == "DIM0127") {
    x = 0;
    y = 300;
  } else if (disciplines[id].code == "DIM0128") {
    x = 0;
    y = 600;
  }
  disciplines[id].selected = false;
  initNodes.push({
    id: id.toString(),
    type: "custom",
    data: disciplines[id],
    position: { x: x, y: y },
    selectable: false,
  });
  x += 200;
}

const initEdges = [
  {
    id: "e0-5",
    source: "0",
    target: "5",
    type: "step",
  },
  {
    id: "e0-6",
    source: "0",
    target: "6",
    type: "step",
  },
  {
    id: "e0-7",
    source: "0",
    target: "7",
    type: "step",
  },
  {
    id: "e0-8",
    source: "0",
    target: "8",
    type: "step",
  },
];

export default function App() {
  const [nodes, setNodes, onNodesChange] = useNodesState(initNodes);
  const [edges, setEdges, onEdgesChange] = useEdgesState(initEdges);

  return (
    <>
      <Head>
        <title>Discc | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{ width: "100vw", height: "100vh" }}>
        <ReactFlow
          nodes={nodes}
          edges={edges}
          onNodeClick={(event, node) => {
            // Updates all nodes
            setNodes((nds) =>
              nds.map((n) => {
                if (n.id === node.id) {
                  // Check if parentes are selected

                  // it's important that you create a new object here
                  // in order to notify react flow about the change
                  n.data = { ...n.data, selected: !n.data.selected };
                }

                return n;
              })
            );
          }}
          nodeTypes={nodeTypes}
          fitView
          className="bg-teal-50"
        >
          <MiniMap />
          <Controls />
        </ReactFlow>
      </main>
    </>
  );
}
