import Head from "next/head";
import ReactFlow from "reactflow";
import "reactflow/dist/style.css";

export default function Home() {
  const disciplines = ["Grafos", "EDB", "LPCP", "FMC", "Blah"];

  const initialNodes = [
    { id: "1", position: { x: 0, y: 0 }, data: { label: "1" } },
    { id: "2", position: { x: 0, y: 100 }, data: { label: "2" } },
  ];
  const initialEdges = [{ id: "e1-2", source: "1", target: "2" }];
  return (
    <>
      <Head>
        <title>Discc | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <div style={{ width: "100vw", height: "100vh" }}>
          <ReactFlow nodes={initialNodes} edges={initialEdges} />
        </div>
    </>
  );
}
